/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.attributes.index": [],
    "filament.admin.resources.attributes.create": [],
    "filament.admin.resources.attributes.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.categories.index": [],
    "filament.admin.resources.categories.create": [],
    "filament.admin.resources.categories.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.customers.index": [],
    "filament.admin.resources.customers.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.media.index": [],
    "filament.admin.resources.orders.index": [],
    "filament.admin.resources.orders.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.orders.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.payment-webhooks.index": [],
    "filament.admin.resources.payment-webhooks.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.payments.index": [],
    "filament.admin.resources.payments.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.products.index": [],
    "filament.admin.resources.products.create": [],
    "filament.admin.resources.products.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.transactions.index": [],
    "filament.admin.resources.transactions.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "default.livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "home": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "catalog.show": [
        {
            "name": "locale",
            "required": true
        },
        {
            "name": "slug",
            "required": true
        }
    ],
    "product.show": [
        {
            "name": "locale",
            "required": true
        },
        {
            "name": "slug",
            "required": true
        }
    ],
    "search": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "login": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "login.check": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "register": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "register.store": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "logout": [
        {
            "name": "locale",
            "required": true
        }
    ],
    "newsletter.subscribe": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
